language: php

services:
    - docker

script:
- docker-compose down -v
- docker-compose build mainapp
- docker-compose up -d mainapp db
- docker exec -it ape_mainapp_1 bash -c cd /var/www/ape && composer test
- bash <(curl -s https://codecov.io/bash)
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker-compose down -v
- docker-compose build mainapp
- docker-compose build db
- docker-compose up -d mainapp db
