language: php

services:
    - docker
    
php:
    - 7.2
    - 7.3

jobs:
  include:
    - stage: Build and push docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t ape-autobuild-travis .
      - docker images
      - docker tag ape-autobuild-travis $DOCKER_USERNAME/ape-autobuild-travis
      - docker push $DOCKER_USERNAME/ape-autobuild-travis
    - stage: Run unittests
      before_script:
      - curl -sSfL -o ~/.phpenv/versions/hhvm/bin/phpunit https://phar.phpunit.de/phpunit-5.7.phar
      - travis_retry composer self-update
      - travis_retry composer install --prefer-source --no-interaction
      script:
      - composer test
      after_script:
      - bash <(curl -s https://codecov.io/bash)

