language: php
dist: trusty

matrix:
    include:
        php:
            - 7.1
            - 7.2

before_script:
    - travis_retry composer self-update
    - travis_retry composer global require "fxp/composer-asset-plugin:~1.0.0"
    - travis_retry composer install --prefer-source --no-interaction


script:
    - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)

