version: '3'

services:
    mainapp:
        build:
            context: .
            dockerfile: ./.docker/Dockerfile.ape
        ports:
            - "8080:80"
        depends_on:
            - db
    pytest:
        build:
            context: .
            dockerfile: ./.docker/Dockerfile.category
        depends_on:
            - db
        ports:
            - "8081:80"
              #    categoryapp:
              #        build:
              #            context: .
              #            dockerfile: ./.docker/Dockerfile.category
              #        depends_on:
              #            - db
    db:
        image: mysql:latest
        command: --init-file /application/.docker/setup.sql
        volumes:
            - ./:/application/
        ports:
            - "3307:3306"
