version: 2 # use CircleCI 2.0

jobs:
  install:
    docker:
      - image: circleci/php:7.2-apache
    parallelism: 4
    working_directory: ~/ape
    steps:
      - checkout
      - setup_remote_docker
      - run: sudo docker-php-ext-install zip pdo
      - run: sudo composer self-update
      - restore_cache: 
          keys:
            - composer-v1-{{ checksum "composer.lock" }}
            - composer-v1-
  test:
    docker:
      - image: circleci/php:7.2-apache
    parallelism: 4
    working_directory: ~/ape
    steps:
      - run: 
          name: Composer install and Unittests
          command: |
            composer install -n --prefer-dist
            composer test
  build:
    docker:
      - image: circleci/php:7.2-apache
    parallelism: 4
    working_directory: ~/ape
    steps:
      - run:
          name: Docker compose
          command: docker-compose -f docker-compose.yml build
  deploy:
    docker:
      - image: circleci/php:7.2-apache
    parallelism: 4
    working_directory: ~/ape
    steps:
      - run:
          name: Build and Deploy Docker Image
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker build \
                -t ashermancinelli/ape-autobuild-circle-$CIRCLE_BRANCH \
                -f .docker/Dockerfile.ape .
            docker push ashermancinelli/ape-autobuild-circle-$CIRCLE_BRANCH
      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor
workflows:
  version: 2
  all:
    jobs:
      - install
      - test:
          requires:
            - install
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build
